# sonar.projectKey=wMind-AI-Server
# sonar.projectName=wMind AI Server
# sonar.sources=.
# sonar.exclusions=**/node_modules/**,**/dist/**
# sonar.host.url=http://localhost:9000
# sonar.token=sqp_aee53130591d9e1a4145469fb2cfa4083c67aa0b


sonar.projectKey=yashkhandagale-dotcom_wmind
sonar.organization=yashkhandagale-dotcom
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**