# sonar.projectKey=wMind-Frontend
# sonar.projectName=wMind Frontend
# sonar.sources=src
# sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.test.tsx
# sonar.host.url=http://localhost:9000
# sonar.token=sqp_8fc22e20a966e95481ac0fe4683c8205df7a565e



sonar.projectKey=yashkhandagale-dotcom_wmind
sonar.organization=yashkhandagale-dotcom
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.test.tsx
sonar.host.url=https://sonarcloud.io