// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Infrastructure.Data;

#nullable disable

namespace MyApp.Infrastructure.Migrations.AssetDbContextForDeviceMigrations
{
    [DbContext(typeof(AssetDbContextForDevice))]
    [Migration("20260225064825_MinMaxThreshold")]
    partial class MinMaxThreshold
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Domain.Entities.AssetSignalDeviceMapping", b =>
                {
                    b.Property<Guid>("MappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DevicePortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OpcUaNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RegisterAdress")
                        .HasColumnType("int");

                    b.Property<string>("SignalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SignalTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SignalUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("registerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MappingId");

                    b.ToTable("MappingTable", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Signal", b =>
                {
                    b.Property<Guid>("SignalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("MaxThreshold")
                        .HasColumnType("float");

                    b.Property<double?>("MinThreshold")
                        .HasColumnType("float");

                    b.Property<Guid?>("OpcUaNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RegisterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SignalKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SignalId");

                    b.ToTable("Signals", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.SignalType", b =>
                {
                    b.Property<Guid>("SignalTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DefaultRegisterAdress")
                        .HasColumnType("int");

                    b.Property<double?>("MaxThreshold")
                        .HasColumnType("float");

                    b.Property<double?>("MinThreshold")
                        .HasColumnType("float");

                    b.Property<string>("SignalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignalUnit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SignalTypeID");

                    b.ToTable("SignalTypes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
