// src/tours/dashboardTour.ts

export const dashboardTour = [
  // Sidebar steps
  // {
  //   element: "#sidebar-dashboard",
  //   popover: { title: "Dashboard", description: "Navigate to the dashboard." },
  // },
  // {
  //   element: "#sidebar-assets",
  //   popover: { title: "Assets", description: "Go to the assets page." },
  // },
  // {
  //   element: "#sidebar-reports",
  //   popover: { title: "Reports", description: "Go to the reports page." },
  // },
  // {
  //   element: "#sidebar-devices",
  //   popover: { title: "Devices", description: "Manage and monitor devices." },
  // },
  // {
  //   element: "#sidebar-signal",
  //   popover: { title: "Signal", description: "Check live and historical signals." },
  // },
  // // Admin only items (filtered if not present in DOM)
  // {
  //   element: "#sidebar-manage-user",
  //   popover: { title: "Manage Users", description: "Admin only: Manage users and roles." },
  // },
  // {
  //   element: "#sidebar-deleted-devices",
  //   popover: { title: "Deleted Devices", description: "Admin only: View deleted devices." },
  // },
  // {
  //   element: "#sidebar-deleted-assets",
  //   popover: { title: "Deleted Assets", description: "Admin only: View deleted assets." },
  // },

  // // Topbar steps
  // {
  //   element: "#topbar-tour-btn",
  //   popover: { title: "Start Tour", description: "Click here to start the guided tour." },
  // },
  // {
  //   element: "#topbar-notifications",
  //   popover: { title: "Notifications", description: "Check alerts and notifications here." },
  // },
  // {
  //   element: "#topbar-user",
  //   popover: { title: "User Profile", description: "Access profile and logout options here." },
  // },

  // Dashboard KPI Steps
  {
    element: "#kpi-plants",
    popover: {
      title: "Plants",
      description: "Total number of plants registered in your manufacturing system.",
      position: "bottom",
    },
  },
  {
    element: "#kpi-departments",
    popover: {
      title: "Departments",
      description: "Departments inside each plant. This helps in understanding the structure.",
      position: "bottom",
    },
  },
  {
    element: "#kpi-assets",
    popover: {
      title: "Total Assets",
      description: "All assets across all plants and departments.",
      position: "bottom",
    },
  },
  {
    element: "#kpi-devices",
    popover: {
      title: "Devices",
      description: "Live connected devices and offline devices (admin only).",
      position: "bottom",
    },
  },
  {
    element: "#kpi-alerts",
    popover: {
      title: "Alerts Today",
      description: "Shows real-time alerts generated by devices today.",
      position: "bottom",
    },
  },

  // Dashboard Stats
  {
    element: "#stat-uptime",
    popover: {
      title: "System Uptime",
      description: "Shows uptime percentage of the entire system.",
      position: "top",
    },
  },
  {
    element: "#stat-efficiency",
    popover: {
      title: "Efficiency",
      description: "Plant performance efficiency based on last calculations.",
      position: "top",
    },
  },
  {
    element: "#stat-response",
    popover: {
      title: "Avg Response Time",
      description: "Average device-to-server communication delay.",
      position: "top",
    },
  },
  {
    element: "#stat-critical",
    popover: {
      title: "Critical Issues",
      description: "Shows critical alerts that need immediate attention.",
      position: "top",
    },
  },

  // Dashboard Charts
  {
    element: "#chart-device-status",
    popover: {
      title: "Device Status Chart",
      description: "Visual representation of active and offline devices.",
      position: "right",
    },
  },
  {
    element: "#chart-performance",
    popover: {
      title: "Performance Metrics",
      description: "Shows performance stats for the past 8 hours.",
      position: "left",
    },
  },
];
